# -*- coding: utf-8 -*-
"""BearingFault_Predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RPaVBBWlc6zm21ZUPimiO7BlXOR8oxDK
"""

from google.colab import drive
drive.mount('/content/drive')

import joblib
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

model_path = '/content/drive/MyDrive/AI_Project/Code_joblib/rf_model.joblib'

rf_model = joblib.load(model_path)


new_data_path = '/content/drive/MyDrive/AI_Project/Data/new_data.csv' #change the name and path to file name and path
new_data = pd.read_csv(new_data_path)


print("Columns: ", df_new.columns)
print("Shape: ", df_new.shape)

if 'Label' in df_new.columns:
  y_true = df_new['Label']
  encoder = LabelEncoder()
  y_true_encoded = encoder.fit_transform(y_true)
  x_new = df_new.drop('Label', axis=1)
else:
  x_new = df_new

y_pred = rf_model.predict(x_new)

print("\nPredicted labels: ", y_pred)
print("\nClassification Report: ", classification_report(y_true_encoded, y_pred))
print("\nConfusion Matrix: ", confusion_matrix(y_true_encoded, y_pred))
print("\nAccuracy Score: ", accuracy_score(y_true_encoded, y_pred))